<?php
/**
 * Template Name: Home Template
 * Template Post Type: post, page
 *
 * @package WordPress
 * @subpackage Twenty_Twenty
 * @since Twenty Twenty 1.0
 */

get_header();
?>

<section class="gp-component-id-Uf42aN3uY gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="79398" data-gp-block="true" data-gp-block-data="{" id":79398,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" empty_50-50.png","category":"empty="" blocks","tag":"blue-theme","user_id":"global","filename":"_empty_2"}"="" data-gp-component-id="Uf42aN3uY" id="Uf42aN3uY" tabindex="0" style=""><a name="Uf42aN3uY" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-3uZ_0t5Qsi gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="3uZ_0t5Qsi" data-gp-component="container" tabindex="0">
            <div class="gp-component-id-jBGtmZ7XSs gp-component" data-gp-component="layout-2-2" data-gp-dnd="" data-gp-style="" data-gp-component-id="jBGtmZ7XSs" tabindex="0" style=""><div class="gp-component-id-kk01C1juts">
                    <div class="gp-component-id-0uC7E4louY" data-gp-grid-col="">
                        <div class="gp-component-id-liMl2MJ3oI gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="liMl2MJ3oI" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component gp-component-id-AwZTuLZWr" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="AwZTuLZWr" data-gp-component="null" tabindex="0"></div><div class="gp-text-container gp-component-id-hwYW0sfeER gp-component" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" style="" data-gp-component-id="hwYW0sfeER" data-gp-component="null" tabindex="0"><h1 class="gp-component-id-8JRmzw4M8" data-id="quill-node-0">&nbsp;Let's begin with a chat about</h1><p class="gp-component-id-8JRmzw4M8" data-id="quill-node-1">&nbsp;&nbsp;&nbsp;&nbsp;your vision and goals!&nbsp;&nbsp;</p></div></div>
                    </div>
                    <div class="gp-component-id-hlu1PQodnr" data-gp-grid-col="">
                        
                    </div>
                </div></div>
        </div>
    </section>
    <section class="gp-component-id-YMuDc6SnY gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="79395" data-gp-block="true" data-gp-block-data="{" id":79395,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" empty.png","category":"empty="" blocks","tag":"blue-theme","user_id":"global","filename":"_empty_0"}"="" data-gp-component-id="YMuDc6SnY" id="YMuDc6SnY" tabindex="0" style=""><a name="YMuDc6SnY" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-UdX4DkLcYE gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="UdX4DkLcYE" data-gp-component="container" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/aHR0cHM6Ly9hc3NldHMuZ3Jvb3ZlYXBwcy5jb20vaW1hZ2VzLzc5MjYxZjM5LTAzZDctNDY5Ni1iNDg3LTY2MDY0OWIzZDdkMy8xNjg4NjM4OTU0X0lNRzkzMTAuanBn.webp" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-GrFGsecv9" data-gp-style="" data-gp-dnd="" data-gp-component="image" data-gp-component-id="GrFGsecv9" tabindex="0"><div class="gp-text-container gp-component gp-component-id-Iy0Ev0gJC" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="Iy0Ev0gJC" tabindex="0" data-gp-component="null"></div></div>
</section><section class="gp-component-id-UVbk7OU20 gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="79395" data-gp-block="true" data-gp-block-data="{" id":79395,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" empty.png","category":"empty="" blocks","tag":"blue-theme","user_id":"global","filename":"_empty_0"}"="" data-gp-component-id="UVbk7OU20" id="UVbk7OU20" tabindex="0" style=""><a name="UVbk7OU20" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-zFJem3Fu_J gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="zFJem3Fu_J" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component gp-component-id-JL0FglMuN" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="JL0FglMuN" data-gp-component="null" tabindex="0" style=""><h2 class="gp-component-id-x9Ccgy6tLr" data-id="quill-node-0">I work with clients to get them FIT for Life</h2></div><div class="gp-text-container gp-component gp-component-id-X1rT7T2GFt" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="X1rT7T2GFt" data-gp-component="null" tabindex="0"><div class="gp-text-container gp-component-id-UZ_FWcYvQ gp-component" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" tabindex="0" style="" data-gp-component-id="UZ_FWcYvQ"><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-0">Would you like to… wake up feeling energized, happy, positive, loving yourself</p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-1">and loving what you see in the mirror?</p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-2"><br></p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-3">Would you like to… Kick start your life, your passion, your health, and your mindset?</p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-4">If so - this is where I can help!</p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-5"><br></p><p class="gp-component-id-oT0x30EXQn" data-id="quill-node-6">I offer a 3- stage plan to create the lifestyle, kick ass mindset and body you have always wanted and desired in just 20 minutes a day.</p></div></div></div>
</section><section class="gp-component-id-uIHkI4M1g gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="79398" data-gp-block="true" data-gp-block-data="{" id":79398,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" empty_50-50.png","category":"empty="" blocks","tag":"blue-theme","user_id":"global","filename":"_empty_2"}"="" data-gp-component-id="uIHkI4M1g" id="uIHkI4M1g" tabindex="0" style=""><a name="uIHkI4M1g" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-XrN4dgP7tT gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="XrN4dgP7tT" data-gp-component="container" tabindex="0">
            <div class="pl-4 pr-4 gp-component gp-component-id-eLtamWkLUI" data-gp-dnd="" data-gp-style="" data-gp-classes="" data-gp-component="layout-2-2" data-gp-component-id="eLtamWkLUI" tabindex="0" style="">
      <div class="md:flex flex-wrap -ml-4 -mr-4">
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
                        <div class="gp-component-id-ZcNs9R86u7 gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="ZcNs9R86u7" data-gp-component="container" style="" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/1653504549oMpAz-DN-9I.jpg" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-Nspcy710V" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="image" data-gp-component-id="Nspcy710V" tabindex="0" style=""></div>
                    </div>
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
                        <div class="gp-component-id-okWJn3BuPD gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="okWJn3BuPD" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component-id-oeoTunzow7 gp-component" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="oeoTunzow7" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-pgilLREvi" data-id="quill-node-0">Let's get to know each other...</h2></div><div class="gp-text-container gp-component gp-component-id-ObG2V9Sxg" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="ObG2V9Sxg" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-FSPBYYkdDn" data-id="quill-node-0">I work as a Mindset Coach for Health and Wellbeing, empowering my clients to live the life they truly want.</p></div><div class="gp-text-container gp-component gp-component-id-cIVFYZ9vEi" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="cIVFYZ9vEi" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-cKxwEoEVU4" data-id="quill-node-0"><strong>When I meet new clients they tend to want to work on some or all of the following:</strong></p><p class="gp-component-id-cKxwEoEVU4" data-id="quill-node-1">-Stuck, lacking direction, motivation or energy</p><p class="gp-component-id-cKxwEoEVU4" data-id="quill-node-2">-Struggling to identify and work towards their goals</p><p class="gp-component-id-cKxwEoEVU4" data-id="quill-node-3">-Wanting to achieve more and be the best they can be</p></div></div>
                    </div>
      </div>
    </div>
        </div>
    </section><section class="gp-component-id-4W3rVyDIo gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="79395" data-gp-block="true" data-gp-block-data="{" id":79395,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" empty.png","category":"empty="" blocks","tag":"blue-theme","user_id":"global","filename":"_empty_0"}"="" data-gp-component-id="4W3rVyDIo" id="4W3rVyDIo" tabindex="0" style=""><a name="4W3rVyDIo" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-IRuXqB2Pkj gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="IRuXqB2Pkj" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component gp-component-id-xtAMpB1tx" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="xtAMpB1tx" data-gp-component="null" tabindex="0"></div><div class="gp-component-id-Vbm0fKk2c gp-component" data-gp-dnd="" data-gp-style="" data-gp-component="layout-1" data-gp-component-id="Vbm0fKk2c" tabindex="0" style="">
      <div class="gp-component-id-1HI5vgQ4N">
        <div class="gp-component-id-_tx0YPW2Kq" data-gp-grid-col="">
          <div class="gp-component-id-i_KN4Czfir gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="i_KN4Czfir" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component gp-component-id-M4xLwbwIBM dndbefore-bottom" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="M4xLwbwIBM" data-gp-component="null" style="" tabindex="0"><h3 class="gp-component-id-EtVFHN5Ny" data-id="quill-node-0">Work with me</h3></div><div class="gp-text-container gp-component gp-component-id-C5zCECexR" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="C5zCECexR" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-ovTjQTNA0s" data-id="quill-node-0">If you are ready to kick start your life...I can help</h2><p class="gp-component-id-ovTjQTNA0s" data-id="quill-node-1">I take advantage of the mind-body connection to work with you as a whole to achieve quick and lasting change - I use some or all of the following to help you achieve the life you really want .....</p></div></div>
        </div>
      </div>
    </div><div class="pl-4 pr-4 gp-component gp-component-id-HaAR8TL5N" data-gp-dnd="" data-gp-style="" data-gp-classes="" data-gp-component="layout-2-2" data-gp-component-id="HaAR8TL5N" tabindex="0" style="">
      <div class="md:flex flex-wrap -ml-4 -mr-4">
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
          <div class="gp-component-id-jwpilK9qKw gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="jwpilK9qKw" data-gp-component="container" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/1653588346rX36vcriciQ.jpg" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-ezvb9ADUX" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="image" data-gp-component-id="ezvb9ADUX" tabindex="0"><div class="gp-text-container gp-component gp-component-id-GMhteSJFN" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="GMhteSJFN" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-WBFXxIOpup">The benefits of &nbsp;121 Online Personal Training</h2></div><div class="gp-text-container gp-component gp-component-id-LZN5jaSJx" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="LZN5jaSJx" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-GWlcs2BAWu">Will help you to develop unshakeable confidence, a kick-ass mindset, body coordination along with fitness, stamina and the lean body you have always dreamed of. As an added bonus you will learn a few ‘funky’ self-defence moves in the process.</p></div><a target="_blank" href="https://garthdelikan.youcanbook.me" data-gp-button-id="7vaBMeUTV" class="dndbefore-bottom gp-component gp-component-id-3oINSXU1R" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="link" data-gp-component-id="3oINSXU1R">
  Book  a call 
</a></div>
        </div>
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
          <div class="gp-component-id-JhCj150gDQ gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="JhCj150gDQ" data-gp-component="container" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/1653842789FO7bKvgETgQ.jpg" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-8QCsjRgEO dndbefore-bottom" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="image" data-gp-component-id="8QCsjRgEO" tabindex="0" style=""><div class="gp-text-container gp-component-id-LIflnZNED gp-component" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="LIflnZNED" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-k4K0xdIMY_">Work-Life- Balance</h2></div><div class="gp-text-container gp-component-id-i6JEWZSiNh gp-component dndbefore-bottom" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="i6JEWZSiNh" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-eSZSx7xwC" data-id="quill-node-0">What is work-life balance, and why is it important? Your overall physical, emotional, and mental health should be your main concern. &nbsp; When creating a schedule that works for you, think about the best way to achieve balance at work and in your personal life. Work-life balance is less about dividing the hours in your day evenly between work and personal life and, instead, is more about having the flexibility to get things done in your professional life while still having time and energy to enjoy your personal life. &nbsp;</p><p class="gp-component-id-eSZSx7xwC" data-id="quill-node-1"> &nbsp;</p></div><a target="_blank" href="https://garthdelikan.youcanbook.me" data-gp-button-id="Og83h7BEZ" class="dndbefore-bottom gp-component gp-component-id-5kw3RpsGe" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="link" data-gp-component-id="5kw3RpsGe">
  Book a call 
</a></div>
        </div>
      </div>
    </div><div class="pl-4 pr-4 gp-component gp-component-id-S8vVD7dPt" data-gp-dnd="" data-gp-style="" data-gp-classes="" data-gp-component="layout-2-2" data-gp-component-id="S8vVD7dPt" tabindex="0" style="">
      <div class="md:flex flex-wrap -ml-4 -mr-4">
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
          <div class="gp-component gp-component-id-CnKziT1AIo" data-gp-container="" data-gp-style="" data-gp-component-id="CnKziT1AIo" data-gp-component="container" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/1653588931Vc1pJfvoQvY.jpg" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-7SMP2p_np" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="image" data-gp-component-id="7SMP2p_np" tabindex="0" style=""><div class="gp-text-container gp-component gp-component-id-TC5FIAm4m" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="TC5FIAm4m" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-z0gcMXhtHu">The benefits of Life Coaching</h2></div><div class="gp-text-container gp-component gp-component-id-fV0Fcwa05P" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="fV0Fcwa05P" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-i2DjoVXeWz">I use a combination of life coaching, Neuro-Linguistic Programming and Hypnotherapy to help you bring about the change you are looking for in your life. We will identify what you really want in life, set goals and put in place strategies that will enable you to achieve your goals and get the life you really want.</p></div><a target="_blank" href="https://garthdelikan.youcanbook.me" data-gp-button-id="-iIx926CQ" class="dndbefore-bottom gp-component gp-component-id-skci40acd" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="link" data-gp-component-id="skci40acd">
  Book a call 
</a></div>
        </div>
        <div class="md:w-1/2 w-full flex-none pl-4 pr-4" data-gp-grid-col="">
          <div class="gp-component gp-component-id-9gqizuCxpv" data-gp-container="" data-gp-style="" data-gp-component-id="9gqizuCxpv" data-gp-component="container" tabindex="0"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/1653588885-YHSwy6uqvk.jpg" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-dAp75y7Ia0" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="image" data-gp-component-id="dAp75y7Ia0" style="" tabindex="0"><div class="gp-text-container gp-component gp-component-id-wc49GDT0uP" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="wc49GDT0uP" data-gp-component="null" style="" tabindex="0"><h2 class="gp-component-id-Y3Vt0y2BZY">The benefits of a heathy diet</h2></div><div class="gp-text-container gp-component gp-component-id-YpFEWFMGh4" data-gp-style="true" data-gp-text="true" data-gp-dnd="true" data-gp-component-id="YpFEWFMGh4" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-VtmxbUcEjt">A health mind and a healthy body starts with what you fuel your mind and body with - lets not forget that this is inter-connected. I work to understand your unique lifestyle and eating habits to come up with a way of eating that will achieve the lasting results you are looking for easily and without dieting.</p></div><a target="_blank" href="https://garthdelikan.youcanbook.me" data-gp-button-id="irlcZKhaq" class="dndbefore-bottom gp-component gp-component-id-zaXG1zS3xP" data-gp-style="" data-gp-dnd="" data-gp-classes="" data-gp-component="link" data-gp-component-id="zaXG1zS3xP">
  Book a call 
</a></div>
        </div>
      </div>
    </div></div>
</section>

<?php get_template_part( 'template-parts/footer-menus-widgets' ); ?>

<?php
get_footer();
