<?php
/**
 * Template Name: Hypnotherapy Template
 * Template Post Type: post, page
 *
 * @package WordPress
 * @subpackage Twenty_Twenty
 * @since Twenty Twenty 1.0
 */

get_header();
?>

<section class="gp-component-id-wV3KKVn5l gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="11978" data-gp-block="true" data-gp-block-type="block" data-gp-block-data="{" id":11978,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" content9.png","category":"content","tag":"wireframe","user_id":"global","filename":"_content_8","height":0,"global":1,"tailwind":1}"="" data-gp-component-id="wV3KKVn5l" style="" id="wV3KKVn5l" tabindex="0"><a name="wV3KKVn5l" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-cwJNa70agk gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="cwJNa70agk" data-gp-component="container" tabindex="0"><div class="gp-text-container gp-component gp-component-id-wN3eVjp1M4" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="wN3eVjp1M4" data-gp-component="null" tabindex="0"><p class="gp-component-id-ZHc9XL8Bke" data-id="quill-node-0">HYPNOTHERAPY</p></div><div class="gp-text-container gp-component gp-component-id-uS4HPwxOCi" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="uS4HPwxOCi" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-80zLR6v0kM" data-id="quill-node-0"><strong>If you feel like you’re screaming at the world, living off coffee and hoping for a miracle to change your life….</strong></p><h2 class="gp-component-id-80zLR6v0kM" data-id="quill-node-1">Hypnotherapy, is a powerful tool that helps you tap in to your unconscious mind to make changes and unlock your hidden potential to make lasting changes quickly. I use hypnotherapy with my clients to help them solve many problems such as …</h2></div></div>
    </section><section class="gp-component-id-nc8ppDHrt gp-component" data-gp-component="block" data-gp-style="" data-gp-block-id="12133" data-gp-block="true" data-gp-block-type="block" data-gp-block-data="{" id":12133,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" gallery9.png","category":"gallery","tag":"wireframe","user_id":"global","filename":"_gallery_8","height":0,"global":1,"tailwind":1}"="" data-gp-component-id="nc8ppDHrt" style="" id="nc8ppDHrt" tabindex="0"><a name="nc8ppDHrt" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component-id-4uTQZ0BwAq gp-component" data-gp-container="" data-gp-style="" data-gp-component-id="4uTQZ0BwAq" data-gp-component="container" tabindex="0"><div class="gp-component-id-ZMvnOz5VS6 gp-component" data-gp-component="layout-2-2" data-gp-style="" data-gp-component-id="ZMvnOz5VS6">
                <div class="gp-component gp-component-id-qOuA5SsMDZ" data-gp-container="" data-gp-style="" data-gp-component-id="qOuA5SsMDZ" data-gp-component="container" tabindex="0">
                    <img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/aHR0cHM6Ly9hc3NldHMuZ3Jvb3ZlYXBwcy5jb20vaW1hZ2VzLzc5MjYxZjM5LTAzZDctNDY5Ni1iNDg3LTY2MDY0OWIzZDdkMy8xNjg0NTA3MDE1X1VudGl0bGVkZGVzaWduNC5wbmc.webp" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-deBnCgtH0M" data-gp-style="" data-gp-dnd="" data-gp-component="image" data-gp-component-id="deBnCgtH0M" tabindex="0">
                </div>
                <div class="gp-component gp-component-id-k8OltmmQgH" data-gp-container="" data-gp-style="" data-gp-component-id="k8OltmmQgH" data-gp-component="container" tabindex="0">
                    <div class="gp-text-container gp-component gp-component-id-HHsnORptCg" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="HHsnORptCg" data-gp-component="null" style="" tabindex="0"><h4 class="gp-component-id-J798eACtRR" data-id="quill-node-0" style="text-align: center;">BREAKING THE HIDDEN CHAINS</h4><p class="gp-component-id-J798eACtRR" data-id="quill-node-1" style="text-align: center;">OF CONTROLLING RELATIONSHIPS</p></div>
                    <div class="gp-text-container gp-component gp-component-id-7YQgxvHG3l" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="7YQgxvHG3l" data-gp-component="null" tabindex="0"><p class="gp-component-id-3O0f5TvRYR" data-id="quill-node-0"><strong>Do you feel like your life is being controlled be others, are you doubting yourself and your ability to make decisions?�&nbsp;</strong>I work with clients everyday who have been or are in controlling relationships with parents, colleagues or partners and they do not realise the long-term impact these relationships cause. Clients feel they are going mad, are unable to make decisions and unable to break the cycle and leave. Or worse still, they do not realise the cycle of abuse they are involved in but feel they have lost their self esteem and do not feel good enough. But help is here so please do not worry any longer.</p><p class="gp-component-id-3O0f5TvRYR" data-id="quill-node-1">There are 9 steps that controlling people follow to create this prison and I will take you through the 9 steps to unwind the spell you are under. I would love the opportunity to help and if you want to know a little more, please google Trauma Bonding.</p></div>
                </div>
            </div></div>
    </section><section class="gp-component gp-component-id-9Zy8WBxiz textediting" data-gp-component="block" data-gp-style="" data-gp-block-id="12133" data-gp-block="true" data-gp-block-type="block" data-gp-block-data="{" id":12133,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" gallery9.png","category":"gallery","tag":"wireframe","user_id":"global","filename":"_gallery_8","height":0,"global":1,"tailwind":1}"="" data-gp-component-id="9Zy8WBxiz" id="9Zy8WBxiz" tabindex="0" style=""><a name="9Zy8WBxiz" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component gp-component-id-1jxrBYitz" data-gp-container="" data-gp-style="" data-gp-component-id="1jxrBYitz" data-gp-component="container" tabindex="0"><div class="gp-component gp-component-id-x4gAg1_Wju" data-gp-component="layout-2-2" data-gp-style="" data-gp-component-id="x4gAg1_Wju">
                <div class="gp-component gp-component-id-S8XN4dQ0Qp" data-gp-container="" data-gp-style="" data-gp-component-id="S8XN4dQ0Qp" data-gp-component="container" tabindex="0">
                    <div class="gp-text-container gp-component gp-component-id-vBN1ss6Rko" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="vBN1ss6Rko" data-gp-component="null" style="" tabindex="0"><h4 class="gp-component-id-wStBZDEfY0" data-id="quill-node-0" style="text-align: center;">BREAKING THE PATTERNS OF WORRY, RUMINATION AND DEPRESSION</h4></div>
                <div class="gp-text-container gp-component gp-component-id-VkoGaVtqt_" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="VkoGaVtqt_" data-gp-component="null" style="" tabindex="0"><p class="gp-component-id-U5JiEM3OM" data-id="quill-node-0"><strong>Do you ever tap into the voices in your head and wonder who those voices are, are they you or voices from your past, for example your parents’ voices?</strong> A lot of my clients are not aware of the cycles of worry and ruminations that is the constant soundtrack in their mind. They are just aware that they just do not feel good about themselves, are often second guessing their choices and a ruminating constantly which in turn can lead to severe anxiety and worse still depression. By tapping into this self-talk, we can change the soundtrack and reverse the harm this can do and before long clients feel that their world becomes a brighter happier place to be as they start to live in the NOW. Worrying, is living in the future, but what if, whilst rumination focusses on the past, “why did I make those bad decision, why did they say that to me?” Be using hypnosis to re-write your patterns allowing you to live in the NOW you can start to live the life you have always dreamed of.</p></div></div>
                <div class="gp-component gp-component-id-YIfHe1nOeM" data-gp-container="" data-gp-style="" data-gp-component-id="YIfHe1nOeM" data-gp-component="container" tabindex="0">
                    
                    
                <img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/aHR0cHM6Ly9hc3NldHMuZ3Jvb3ZlYXBwcy5jb20vaW1hZ2VzLzc5MjYxZjM5LTAzZDctNDY5Ni1iNDg3LTY2MDY0OWIzZDdkMy8xNjg0NTA3NDA2X1VudGl0bGVkZGVzaWduNS5wbmc.webp" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-d3m2H8IVpQ" data-gp-style="" data-gp-dnd="" data-gp-component="image" data-gp-component-id="d3m2H8IVpQ" tabindex="0"></div>
            </div></div>
    </section><section class="gp-component gp-component-id-us5mlwk5r" data-gp-component="block" data-gp-style="" data-gp-block-id="12133" data-gp-block="true" data-gp-block-type="block" data-gp-block-data="{" id":12133,"type":"block","thumbnail":"https:="" assets.grooveapps.com="" elements-previews="" thumbs="" gallery9.png","category":"gallery","tag":"wireframe","user_id":"global","filename":"_gallery_8","height":0,"global":1,"tailwind":1}"="" data-gp-component-id="us5mlwk5r" id="us5mlwk5r" tabindex="0" style=""><a name="us5mlwk5r" data-gp-block-anchor=""></a>
        <div class="" data-section-overlay=""></div>
        <div class="gp-component gp-component-id-ALRdNe1nwf" data-gp-container="" data-gp-style="" data-gp-component-id="ALRdNe1nwf" data-gp-component="container" tabindex="0"><div class="gp-component gp-component-id-qRxQVEADjU" data-gp-component="layout-2-2" data-gp-style="" data-gp-component-id="qRxQVEADjU">
                <div class="gp-component gp-component-id-TjlvskHXqg" data-gp-container="" data-gp-style="" data-gp-component-id="TjlvskHXqg" data-gp-component="container" tabindex="0">
                    <img src="<?php echo esc_url( get_template_directory_uri() ); ?>/images/aHR0cHM6Ly9hc3NldHMuZ3Jvb3ZlYXBwcy5jb20vaW1hZ2VzLzc5MjYxZjM5LTAzZDctNDY5Ni1iNDg3LTY2MDY0OWIzZDdkMy8xNjg0NTA3NTc2X1VudGl0bGVkZGVzaWduNi5wbmc.webp" alt="" class="inline-flex items-start justify-start object-cover object-center gp-component gp-component-id-jqrVWlm3h7" data-gp-style="" data-gp-dnd="" data-gp-component="image" data-gp-component-id="jqrVWlm3h7" tabindex="0">
                </div>
                <div class="gp-component gp-component-id-q4sDkw00L" data-gp-container="" data-gp-style="" data-gp-component-id="q4sDkw00L" data-gp-component="container" tabindex="0">
                    <div class="gp-text-container gp-component gp-component-id-JWNTUKaH0h" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="JWNTUKaH0h" data-gp-component="null" style="" tabindex="0"><h4 class="gp-component-id-pNch0OQ6Py" data-id="quill-node-0" style="text-align: center;">ARE YOU DESPERATELY TRYING TO LOSE WEIGHT AND KEEP IT OFF?</h4></div>
                    <div class="gp-text-container gp-component gp-component-id-vg0qAgYHgT" data-gp-style="" data-gp-text="" data-gp-dnd="" data-gp-component-id="vg0qAgYHgT" data-gp-component="null" tabindex="0"><p data-id="quill-node-0" class="gp-component-id-ppuDYhaEpA">I find that many of my clients put on more weight than they would like for many reasons, for example if you find yourself in one of the above situations turning to food, or cutting yourself off from the world and staying behind closed doors can lead to comfort eating and lack of exercise. </p><p class="gp-component-id-ppuDYhaEpA" data-id="quill-node-1"><br></p><p class="gp-component-id-ppuDYhaEpA" data-id="quill-node-2">For what ever the reason, hypnotherapy can go exactly to the root cause and allow your unconscious mind to break free from these patterns and unleash the inner you, giving you the control. Tools, techniques and strategies you need to make changes happen.</p></div>
                </div>
            </div></div>
    </section>

<?php get_template_part( 'template-parts/footer-menus-widgets' ); ?>

<?php
get_footer();
